Add clear all recents action to recents panel
Change-Id: I2243ebc83abc483e78b112900a653d7e61edc5ba

Fix - place Clear Recents button above the nav bar

Change-Id: Ie7059cd1f71bae28ff25f367221b7c7ba0131932

Fix up 'clear recents' UX.

Use the 'dismiss all' button drawable and place the button in the upper
right corner. Doing so fixes the broken animation when going into
recents.

Change-Id: I497a8b023f1872c5f9ae5df87af6ed2159e6b7b1

SystemUI: Check if a task's group is null prior to TaskGrouping#isFrontMostTask.

    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean
    com.android.systemui.recents.model.TaskGrouping.isFrontMostTask(com.android.systemui.recents.model.Task)' on a null object reference
      at com.android.systemui.recents.views.RecentsView.onTaskViewClicked(RecentsView.java:535)
      at com.android.systemui.recents.views.TaskStackView.onTaskViewClicked(TaskStackView.java:1125)
      at com.android.systemui.recents.views.TaskView.onClick(TaskView.java:881)
      at android.view.View.performClick(View.java:4756)
      at android.view.View$PerformClick.run(View.java:19749)
      at android.os.Handler.handleCallback(Handler.java:739)
      at android.os.Handler.dispatchMessage(Handler.java:95)

Change-Id: I04afec21a7c4e7ba5b3e51ae76a2065e98e6cfa2

systemui: animate clear recents exit

Currently, the animation just clear all the tasks at the same time. Just add
a delay between every task remove call, and hide clear recents before start
any animation.

Change-Id: Idbdeacc68c6519d28dc875d09cd75c71e2e9f701
Signed-off-by: Jorge Ruesga <jorge@ruesga.com>

systemui: adjust position of clear recents button

If there is a statusbar then align to it. Otherwise aling to task views rather than top/right.
This patch fixed the position in tablets (align it with the search bar) and in landscape mode
(reducing the space between task views and the clear recents button), with is a more consistent
ui because the button is always properly aligned with the recent task views.

Change-Id: Ic867d5421cacba627c4b844db3d3715f20a4444c
Signed-off-by: Jorge Ruesga <jorge@ruesga.com>

systemui: animate clear recents button on exit animation

Change-Id: Ic617f50400558be4ad92a4a5ea3ef441d2afde6a
Signed-off-by: Jorge Ruesga <jorge@ruesga.com>

Conflicts:
	packages/SystemUI/res/values/config.xml
	packages/SystemUI/src/com/android/systemui/recents/RecentsActivity.java
	packages/SystemUI/src/com/android/systemui/recents/views/RecentsView.java
	packages/SystemUI/src/com/android/systemui/recents/views/TaskView.java

DERP on clear recent commit

Change-Id: I79d4368ec255de8e5cc6f7d0bdf366c1ad614a71

Missing clear all recents drawable

Change-Id: I25ffd636bbef5f95d02cea9f875d4b2e4ae4eaac

recentsview derp

Change-Id: I4c00279d457241a43432a045ed9e8e8dd1a9a8be